services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: goal
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  cache:
    image: redis
    ports:
      - 6379:6379
volumes:
  data:
