services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYQSL_DATABASE=goal
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  cache:
    image: redis
    ports:
      - 6379:6379
volumes:
  data:
